config/routes.rb
Rails.application.routes.draw do
  resources :category_quotes
  resources :categories
  root to: "static_pages#home"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } 
  resources :quotes do 
    resources :categories
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    # validates :name, presence: true
    has_many :category_quotes
    has_many :quotes, through: :category_quotes
end

app/models/category_quote.rb
class CategoryQuote < ApplicationRecord
    belongs_to :category
    belongs_to :quote
    def self.most_categories
        if !self.all.empty?
            self.group(:quote_id).count.first[0]
        end
    end
end

app/models/quote.rb
class Quote < ApplicationRecord
    validates :text, :author, presence: true
    has_many :category_quotes
    has_many :categories, through: :category_quotes
 
    def categories_attributes=(categories_attributes)
        if categories_attributes["0"]["name"] != ""
            category = Category.find_or_create_by(categories_attributes["0"])
            self.categories << category
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :quotes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      end
  end
    
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def check
      if !user_signed_in?
        redirect_to root_path, :flash => {:message => "Please Sign In"}
      end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    
    def new
        @quote = Quote.find_by(id: params[:quote_id])
        @category = Category.new
    end
    
    def show
        @category = Category.find_by(id: params[:id])
        respond_to do |f|
        f.html {render :show}
        f.json {render json: @category}
        end
    end

    def index
        # @quote = Quote.find_by(id: params[:quote_id])
        # @categories = @quote.categories
        @categories = Category.all
        respond_to do |f|
        f.html {render :index}
        f.json {render json: @category}
        end
    end
    
    def edit
        @category = Category.find_by(params[:id])
        @quote = Quote.find_by(id: params[:quote_id])
        render json: @category, status: 201
    end

    def create
        category = Category.new(name: category_params["name"])
        category.save
        category_quote = CategoryQuote.new(category_id: category.id, quote_id: category_params["quote_id"])
        category_quote.save
        render json: category, status: 201
        # redirect_to category_path(category)
    end
    
    def update
        category = Category.update(category_params)
        redirect_to category_path(category)
    end
    
    private
    
    def category_params
        params.require(:category).permit(:name, :user_id, :quote_id)
    end
end

app/controllers/category_quotes_controller.rb
class CategoryQuotesController < ApplicationController
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

    def home
       @quotes = current_user.quotes if !check
       render json: @quotes
    end

    def index
       @quotes = Quote.all
       render json: @quotes
    end
    
    def new
        @error = params[:error]
         @quote = Quote.new if !check
    end
    
    def edit
        @quote = Quote.find_by(id: params[:id]) if !check
    end
    
    def show 
        @quote = Quote.find_by(id: params[:id]) 
        @categories = @quote.categories.order("name ASC")
        respond_to do |f|
        f.html {render :show}
        f.json {render json: @quote}
        end
    end 

    def create
        quote = Quote.new(quote_params)
        if quote.save
        redirect_to quote_path(quote)
        else
        @error = quote.errors.full_messages
        redirect_to new_quote_path(:error => @error )
        end
    end

 
    def update
        quote = Quote.find_by(params[:id])
        quote.update(quote_params)
        redirect_to quote_path(quote)
    end

    private

    def quote_params
      params.require(:quote).permit(:text, :author, categories_attributes: [:name], category_ids: [])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @quotes = Quote.all
    if @quotes != []
      @relatable = Quote.find_by(id: CategoryQuote.most_categories)
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
    
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_quotes_helper.rb
module CategoryQuotesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/categories/_form.html.erb
<div id="category">

<%= form_for (category) do |f| %>
    <%=  f.label :name %>
    <%=  f.text_field :name %>
    <%=  f.hidden_field :quote_id, :value => quote.id %>
    <%=  f.submit %>
<% end %>
<div>

<%= javascript_include_tag 'category_form' %>

app/views/categories/edit.html.erb
Edit Category:

 <%= render partial: 'categories/form', locals: {category: @category, quote: @quote} %>

app/views/categories/index.html.erb
<% @categories.each do |category| %>
    <%=  category.name %> <br>
<% end %>

app/views/categories/new.html.erb
 <h3>New Category: <h3>
 <%= render partial: 'categories/form', locals: {category: @category, quote: @quote} %>

app/views/categories/show.html.erb
 <%= javascript_include_tag 'category' %>
<div id="category_name">
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuotesRailsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <nav>
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
      Hi! <%= current_user.email %>
      <li><%= link_to "Sign out", destroy_user_session_path, method: 'DELETE' %></li>
      <li> <%= link_to "Add Quote", new_quote_path %></li>
      <li> <%= link_to "Edit User Account", edit_user_registration_path %></li>
      <li> <%= link_to "Home", root_path %></li>
      <% else %>
      <li>  <%= link_to "Sign Up", new_user_registration_path %> </li>
      <li>  <%= link_to "Sign In", user_session_path %></li>
      <li>  <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %></li>
      <% end %>
    </ul>      
    </div>
    </nav>
     <p class="notice" style="color:red"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/quotes/_form.html.erb
<%= form_for(quote) do |f| %>
    <div class="field">
        <%= f.label :text %><br>
        <%= f.text_area :text %><br>
        <%= f.label :author %><br>
        <%= f.text_field :author %><br>
    </div>
    <div class = "field">
        <p>Select a Category: </p>
         <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
    </div>

    <div class = "field">
       <p>Add a Category:</p>
     <%= f.fields_for :categories, quote.categories.build do |category_fields| %>
                <%= category_fields.label :name %>
                <%= category_fields.text_field :name %>
        <% end %>
    </div>
    <%= f.submit %>
<% end %>

app/views/quotes/edit.html.erb
 <%=  render partial: 'quotes/form', locals: {quote: @quote}%>

app/views/quotes/index.html.erb
<% @quotes.each do |quote| %>
    <%= quote.name %>
        by: <%= quote.author %>
    <%= link_to "Show Categories", quote_categories_path(quote) %>
<% end %>

app/views/quotes/new.html.erb
 <h2 style = "color:red"><%= @error if @error %> </h2>
 <%=  render partial: 'quotes/form', locals: {quote: @quote}%>

app/views/quotes/show.html.erb
<h2><%= @quote.text %></h2>

- <h4><%= @quote.author %></h4>

<h5> Categories </h5>
<ul>
    <% @categories.each do |category|  %>
        <li><%= link_to category.name, category_path(category) %></li>
    <% end %>
</ul>


<%= link_to "Add Original Category", new_quote_category_path(@quote) %><br>
<%= link_to "Edit Quote", edit_quote_path(@quote) %>

app/views/static_pages/home.html.erb
<%= javascript_include_tag 'get_all_quotes' %>
<% if flash[:message] %>
    <%= flash[:message] %>
<% end %>

<h1>quotes app </h1>
    <p>collect the quotes you love!</p>
<h2>Most Relatable Quote Today</h2>
 <h3> <%=  @relatable.text if @relatable %> </h3>
    <h4>By: <%= @relatable.author if @relatable%></h4>

<div id="quotes">
<h3>All Quotes </h3>
<div>